data:
  train_path: "data/01-raw/train.csv"
  test_path: "data/01-raw/test.csv"
  target_column: "Survived"
  model_dir: "models"
  # This matches the folder structure we created earlier
  predictions_path: "data/05_predictions/submission.csv"

preprocessing:
  test_size: 0.2
  random_state: 42
  # We can add feature toggles here later if we want

model:
  type: "SVM"  # Options: SVM, RandomForest
  parameters:
    C: 1
    kernel: "rbf"
    gamma: "scale"
    probability: true
    random_state: 42

logging:
  level: "INFO"
